services:
    ft-transcendence:
        build:
            context: ./client/
            dockerfile: Dockerfile.dev
        image: ft-transcendence:develop
        container_name: ft-transcendence
        ports:
            - 443:443
        volumes:
            - ft-trascendence-vol-client:/var/www/ft_transcendence/:rw
            - ft-trascendence-vol-conf:/etc/nginx/sites-enabled/:rw
        networks:
            - ft_transcendence
        restart: on-failure

    authentication:
        build:
            context: ./services/authentication/
            dockerfile: Dockerfile.dev
        image: authentication:develop
        container_name: authentication
        env_file:
            - ./services/.env
        volumes:
            - ./services/authentication/:/microservice/authentication/:rw
        networks:
            - ft_transcendence
        restart: on-failure

    player:
        build:
            context: ./services/player/
            dockerfile: Dockerfile.dev
        image: player:develop
        container_name:  player
        env_file:
            - ./services/.env
        volumes:
            - ./services/player/:/microservice/player/:rw
        networks:
            - ft_transcendence
        restart: on-failure

networks:
    ft_transcendence:
        name: ft_transcendence
        driver: bridge

volumes:
  ft-trascendence-vol-client:
    driver: local
    name: ft-trascendence-vol-client
    driver_opts:
      type: bind
      o: bind
      device: /Users/ychaaibi/Desktop/ft_transcendence/client/
    
  ft-trascendence-vol-conf:
    driver: local
    name: ft-trascendence-vol-conf
    driver_opts:
      type: bind
      o: bind
      device: /Users/ychaaibi/Desktop/ft_transcendence/client/conf