services:
    ft-transcendence:
        build:
            context: ./client/
            dockerfile: Dockerfile
        image: ft-transcendence:deploy
        container_name: ft-transcendence
        ports:
            - 443:443
        networks:
            - ft_transcendence
        restart: on-failure

    authentication:
        build:
            context: ./services/authentication/
            dockerfile: Dockerfile
        image: authentication:deploy
        container_name: authentication
        env_file:
            - ./services/.env
        networks:
            - ft_transcendence
        restart: on-failure

    player:
        build:
            context: ./services/player/
            dockerfile: Dockerfile
        image: player:deploy
        container_name:  player
        env_file:
            - ./services/.env 
        networks:
            - ft_transcendence
        restart: on-failure

networks:
    ft_transcendence:
        name: ft_transcendence
        driver: bridge