services:
    frontend:
        build:
            context: ./frontend/
            build: Dockerfile.dev
        image: frontend:develop
        container_name: frontend-develop
        ports:
            - 81:81
        volumes:
            - ./frontend:/var/www/ft_transcendence/:ro
        networks:
            - ft_transcendence
        restart: on-failure

    authentication:
        build:
            context: ./services/authentication/
            build: Dockerfile.dev
        image: authentication:develop
        container_name: authentication-develop
        environment: ./services/.env
        volumes:
            - ./services/authentication/:microservice/authentication/:ro
        networks:
            - ft_transcendence
        restart: on-failure

    player:
        build:
            context: ./services/player/
            build: Dockerfile.dev
        image: player:develop
        container_name:  player-develop
        environment: ./services/.env
        volumes:
            - ./services/player/:microservice/player/:ro 
        networks:
            - ft_transcendence
        restart: on-failure

networks:
    ft_transcendence:
        name: ft_transcendence
        driver: bridge