services:
    ft-transcendence:
        build:
            context: ./client/
            dockerfile: Dockerfile.dev
        image: ft-transcendence:develop
        container_name: ft-transcendence
        environment:
            - STAGE=Development
        ports:
            - 443:443
        volumes:
            - ./client:/var/www/ft_transcendence/:rw
            - ./client/conf:/etc/nginx/sites-enabled/:rw
        networks:
            - ft_transcendence
        restart: on-failure

    authentication:
        build:
            context: ./services/authentication/
            dockerfile: Dockerfile.dev
        image: authentication:develop
        container_name: authentication
        environment:
            - STAGE=Development
        env_file:
            - ./services/.env
        volumes:
            - ./services/authentication/:/microservice/authentication/:rw
        networks:
            - ft_transcendence
        restart: on-failure

    player:
        build:
            context: ./services/player/
            dockerfile: Dockerfile.dev
        image: player:develop
        container_name:  player
        environment:
            - STAGE=Development
        env_file:
            - ./services/.env
        volumes:
            - ./services/player/:/microservice/player/:rw
        networks:
            - ft_transcendence
        restart: on-failure

    matchmaking:
        build:
            context: ./services/matchmaking/
            dockerfile: Dockerfile.dev
        image: matchmaking:develop
        container_name:  matchmaking
        environment:
            - STAGE=Development
        env_file:
            - ./services/.env
        volumes:
            - ./services/matchmaking/:/microservice/matchmaking/:rw
        networks:
            - ft_transcendence
        restart: on-failure

    pong:
        build:
            context: ./services/pong/
            dockerfile: Dockerfile.dev
        image: pong:develop
        container_name:  pong
        environment:
            - STAGE=Development
        env_file:
            - ./services/.env
        volumes:
            - ./services/pong/:/microservice/pong/:rw
        networks:
            - ft_transcendence
        restart: on-failure

networks:
    ft_transcendence:
        name: ft_transcendence
        driver: bridge
