services:
    ft-transcendence:
        build:
            context: ./client/
            dockerfile: Dockerfile.dev
        image: ft-transcendence:develop
        container_name: ft-transcendence
        ports:
            - 443:443
        volumes:
            - ./client:/var/www/ft_transcendence/:ro
        networks:
            - ft_transcendence
        restart: on-failure

    authentication:
        build:
            context: ./services/authentication/
            dockerfile: Dockerfile.dev
        image: authentication:develop
        container_name: authentication
        env_file:
            - ./services/.env
        volumes:
            - ./services/authentication/:/microservice/authentication/:rw
        networks:
            - ft_transcendence
        restart: on-failure

    player:
        build:
            context: ./services/player/
            dockerfile: Dockerfile.dev
        image: player:develop
        container_name:  player
        env_file:
            - ./services/.env
        volumes:
            - ./services/player/:/microservice/player/:rw
        networks:
            - ft_transcendence
        restart: on-failure

networks:
    ft_transcendence:
        name: ft_transcendence
        driver: bridge